### ISSUE TITLE
Passing Array Data From Controller to View

### ISSUE THREAD

**Issue by rachmawatiafrida** [biobii/fylite#1]
Cara passing array data dari controller ke view gimana ya om? 

`    public function welcome()
    {
    	$title = "Test";
        return view("welcome",[
        	"judul" => $title
        ]);
    }`

Menggunakan
`<?php echo $judul;?>`
Tidak bisa, atau mungkin salah cara panggilnya?

Terimakasih banyak,

**Comment by rachmawatiafrida** [comment]
Udah bisa om, pakai: 
`    public function welcome()
    {
		$data = [
			'title' => "Ini Judul Ya",
			'ok'	=> "Ini data"
		];
        return view("welcome",$data);
    }`,

Atau mungkin ada cara lain yang lebih baik?

**Comment by rachmawatiafrida** [comment]
Apakah bisa get $config value pada view melalui controller? Tanpa menginclude config.php di view?

**Comment by mohammadrobih** [comment]
Hai @rachmawatiafrida , bila ingin passing data ke view dengan cara seperti ini
`public function welcome() { $title = "Test"; return view("welcome",[ "judul" => $title ]); }` maka untuk pemanggilan di view dapat langsung menggunakan `echo $data['judul'];`

Untuk get variabel $config pada view dimaksudkan untuk kebutuhan seperti apa? Terima kasih.

**Comment by rachmawatiafrida** [comment]
get variabel $config misalkan ingin membuat config untuk meta_title, description, dsb, dan bisa dipanggil ke header.view.php tanpa perlu menginclude file config di header.view.php

**Comment by mohammadrobih** [comment]
Saat ini belum bisa, lebih praktisnya buatkan saja helpers untuk kasus yang kamu inginkan. Terima kasih masukannya.
